# Generated by Django 4.1.12 on 2023-12-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0002_skillenhancement"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillenhancement",
            name="course_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="skillenhancement",
            name="description",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="skillenhancement",
            name="image",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="skillenhancement",
            name="provider",
            field=models.CharField(max_length=50),
        ),
    ]
