# Generated by Django 4.1.12 on 2023-12-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0003_skillenhancement_course_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillenhancement",
            name="price_detail",
            field=models.JSONField(null=True),
        ),
    ]
