# Generated by Django 4.1.12 on 2024-01-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0004_skillenhancement_price_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="plan",
            field=models.CharField(default="free trial", max_length=20),
        ),
    ]
