# Generated by Django 4.1.9 on 2023-06-16 22:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0004_remove_gripuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
