# Generated by Django 4.1.9 on 2023-06-16 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_alter_role_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='job_profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.jobprofile'),
        ),
        migrations.AlterField(
            model_name='role',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
