# Generated by Django 4.1.12 on 2024-01-10 14:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0005_alter_company_plan"),
        ("schema", "0006_alter_oauthuserprofile_user"),
    ]

    operations = []
