# Generated by Django 4.1.9 on 2023-06-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0007_alter_role_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
