# Generated by Django 4.1.12 on 2024-01-16 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0008_alter_gripuser_first_name_alter_gripuser_last_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_name", models.CharField(max_length=100)),
                ("goal_description", models.CharField(max_length=300, null=True)),
                ("start_date", models.DateField()),
                ("due_date", models.DateField(null=True)),
                ("status_of_goal", models.CharField(max_length=50, null=True)),
                ("completed", models.BooleanField(default=False)),
                ("develop_action", models.CharField(max_length=300)),
                ("goal_skills", models.JSONField(null=True)),
                ("goal_course", models.IntegerField(null=True)),
                ("goal_project", models.IntegerField(null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schema.company"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
