# Generated by Django 4.1.9 on 2023-06-18 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0008_alter_role_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerjob',
            name='stage_id',
        ),
        migrations.AlterField(
            model_name='careerjob',
            name='previous_jobs',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
