# Generated by Django 4.1.12 on 2024-01-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schema", "0009_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="activity_description",
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="activity_name",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
