# Generated by Django 4.1.13 on 2024-01-17 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0010_goal_activity_description_goal_activity_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='activity_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='goal_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='status_of_goal',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='activity_name',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='develop_action',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_course',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_description',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_project',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_skills',
        ),
        migrations.CreateModel(
            name='GoalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_id', models.CharField(max_length=50)),
                ('percentage', models.IntegerField(null=True)),
                ('level', models.IntegerField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.company')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.company')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=50, null=True)),
                ('precentage', models.IntegerField(null=True)),
                ('details', models.JSONField(null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.company')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]