# Generated by Django 4.1.9 on 2023-06-18 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0010_alter_role_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerjob',
            name='job_profile_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schema.jobprofile'),
        ),
    ]
