# Generated by Django 4.1.9 on 2023-06-19 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0011_alter_careerjob_job_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gripfile',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
