# Generated by Django 4.1.13 on 2024-01-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0011_rename_activity_description_goal_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalskill',
            name='level',
        ),
        migrations.RemoveField(
            model_name='goalskill',
            name='percentage',
        ),
    ]