# Generated by Django 4.1.9 on 2023-06-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0011_alter_careerjob_job_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='allignment',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
