# Generated by Django 4.1.9 on 2023-06-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0012_role_allignment_delete_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='allignment',
        ),
        migrations.AddField(
            model_name='role',
            name='allign',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='selected_role_id',
            field=models.IntegerField(null=True),
        ),
    ]
