# Generated by Django 4.1.13 on 2024-01-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0012_remove_goalskill_level_remove_goalskill_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalaction',
            old_name='precentage',
            new_name='percentage',
        ),
    ]