# Generated by Django 4.1.9 on 2023-06-24 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0012_gripfile_user_id'),
        ('schema', '0013_remove_role_allignment_role_allign_and_more'),
    ]

    operations = [
    ]
