# Generated by Django 4.1.9 on 2023-06-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0014_merge_20230624_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gripfile',
            old_name='user_id',
            new_name='user',
        ),
    ]
