# Generated by Django 4.1.13 on 2024-01-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0014_goal_skills_delete_goalskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='completed',
        ),
        migrations.AlterField(
            model_name='goalaction',
            name='percentage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]