# Generated by Django 4.1.13 on 2024-01-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0015_remove_goal_completed_alter_goalaction_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalaction',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='schema.goal'),
        ),
    ]