# Generated by Django 4.1.9 on 2023-07-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0015_rename_user_id_gripfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillproficiency',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skillrequirement',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skillwish',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
