# Generated by Django 4.1.9 on 2023-07-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0016_skillproficiency_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillproficiency',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='skillrequirement',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='skillwish',
            name='description',
            field=models.CharField(max_length=700, null=True),
        ),
    ]
