# Generated by Django 4.1.13 on 2024-01-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0017_remove_goalaction_goal_goal_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='action',
        ),
        migrations.AddField(
            model_name='goalaction',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='schema.goal'),
            preserve_default=False,
        ),
    ]
