# Generated by Django 4.1.9 on 2023-07-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0019_remove_careerjob_previous_jobs_careerlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schema.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schema.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schema.company'),
            preserve_default=False,
        ),
    ]
