# Generated by Django 4.1.9 on 2023-08-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0021_alter_gripuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='institution',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
