# Generated by Django 4.1.9 on 2023-08-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0022_alter_course_institution_alter_course_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
