# Generated by Django 4.1.9 on 2023-08-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0023_alter_experience_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
