# Generated by Django 4.1.10 on 2023-09-21 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('schema', '0024_alter_education_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('hours', models.CharField(max_length=50, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=700, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('job_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.jobprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VacancySkill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('skill_ref', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.company')),
                ('vacancy_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='schema.vacancyrole')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectVacancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placeholder1', models.CharField(max_length=50)),
                ('placeholder2', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
                ('description', models.CharField(max_length=700, null=True)),
                ('status', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('ref_post_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.company')),
                ('job_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schema.jobprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
