# Generated by Django 4.1.10 on 2023-09-21 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0025_vacancyrole_vacancyskill_projectvacancy_jobvacancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvacancy',
            name='job_profile',
        ),
    ]
