# Generated by Django 4.1.10 on 2023-10-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0026_remove_jobvacancy_job_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyskill',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
