# Generated by Django 4.1.10 on 2023-10-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0027_vacancyskill_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectvacancy',
            old_name='placeholder1',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='projectvacancy',
            old_name='placeholder2',
            new_name='name',
        ),
        migrations.AddField(
            model_name='projectvacancy',
            name='ref_post_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
