# Generated by Django 4.1.10 on 2023-10-04 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0029_endorsement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endorsement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='schema.skillproficiency'),
        ),
        migrations.AlterField(
            model_name='vacancyrole',
            name='hours',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vacancyrole',
            name='salary',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
