# Generated by Django 4.1.10 on 2023-11-01 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0030_alter_endorsement_skill_alter_vacancyrole_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='department',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectvacancy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vacancyrole',
            name='hours',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
