# Generated by Django 4.1.10 on 2023-11-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0031_alter_jobvacancy_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyrole',
            name='role_ref_id',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
